version: '3.9'
networks:
  app-network: null
services:
  nginx:
    image: nginx:stable-alpine
    container_name: 'nginx_${APP_NAME}'
    ports:
      - '80:80'
    volumes:
      - './src:/var/www/html'
      - './nginx-default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
    networks:
      - app-network
  mysql:
    image: mariadb:10.5.8
    container_name: 'mysql_${APP_NAME}'
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laravel_jwt_api
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'php_${APP_NAME}'
    user: '${UID:-1000}:${GID:-1000}'
    volumes:
      - './src:/var/www/html'
    ports:
      - '9000:9000'
    networks:
      - app-network